name: Hello World Workflow

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: windows-latest
    steps:
      - name: Do something
        id: step_one
        run: |
          curl https://ches.api.gov.bc.ca/api/v1/
